### PR TITLE
Video Description

### PR DESCRIPTION
**Pull request by micahalcorn**
I'm not sure if this requires translation or anything else. 🇰🇷

### CODE REVIEW

**Comment by micahalcorn** [comment]
@sparrowdom they are getting picked up by Google, it seems, which is how I knew to change it. 🧐

**Comment by sparrowDom** [comment]
Ah yes you are right, summaries can be found in the `description` meta tag on the video pages

**Comment by joshfraser** [comment]
Ah, in that case, let's update the summaries for all of the videos.

**Comment by sparrowDom** [comment]
I can do it, though I think I am not the best person to make those summaries. Have put them all in [the document](https://docs.google.com/document/d/1PifMXlMrdXUT-w2xzb_tnEk5C1SPzE2wGGWAn-MH9OE/edit#heading=h.odzw1x39xohw) (see bottom of the doc): 
could perhaps @micahalcorn @joshfraser or @matthewliu do this perhaps? And once you are done just ping me and I can copy them to website code.

**Comment by joshfraser** [comment]
I did it. Thanks.

**Comment by sparrowDom** [comment]
A you did it directly in the code nice!

**Pull request merged**
