### PR TITLE
adds flask-assets to manage static content

### PR DESCRIPTION
**Pull request by Gzing**
Initial setup for packaging static content via flask-assets.
Will be able to use babel and dependent presets to write es6 code. Also, minification and any other packaging needs are handled easily.

Integrates very well with flask-cdn and uses MD5 hashes of files to invalidate cachces, if in future we opt to use a CDN.

### CODE REVIEW

**Comment by micahalcorn** [comment]
Wonderful, thanks @Gzing!

**Comment by micahalcorn** [comment]
@Gzing any idea what should be done with this old PR? I thought that we did end up using flask-assets, but not all of this code made it in. 😕

**Comment by Gzing** [comment]
@micahalcorn thanks for checking this. Will rebase this PR with master and push again :+1:

**Comment by Zero-1729** [comment]
@Gzing Are you still working on this? :confused:

**Comment by micahalcorn** [comment]
@Zero-1729 I don't believe that he is. Let me know if you are interested in working on this or another issue from [our project board](https://github.com/orgs/OriginProtocol/projects/2).

**Comment by joshfraser** [comment]
Closing this as I believe we're all set for now.

**Pull request closed without merging**
