### PR TITLE
Fetch list of Github contributors

### PR DESCRIPTION
**Pull request by joshfraser**
This is a basic script for fetching the list of our contributors to our various repos and storing them in our database along with your beautiful avatars & number of commits. I tried to be smart and only count contributions to our forked repos when you've contributed to a non-forked Origin repo. Thinking we put this script on a nightly cron so we have a fast & easy way to display all our contributors on our /team page as discussed in #154. 

Here are our current stats, btw. Thank you all for being so amazing. We couldn't do this without you.

|   | Username | Commits |
| --- | --- | --- |
||	@wanderingstan|	641|
||	@tyleryasaka|	444|
||	@micahalcorn|	309|
||	@joshfraser|	291|
||	@DanielVF|	112|
||	@matthewliu|	47|
||	@coleman415|	47|
||	@ambertch|	45|
||	@jordajm|	43|
||	@Gzing|	42|
||	@nick|	37|
||	@tomlinton|	36|
||	@sparrowDom|	29|
||	@aiham|	28|
||	@evra6965|	21|
||	@franckc|	17|
||	@ryana|	16|
||	@crazybuster|	11|
||	@mek32390|	10|
||	@davecraige|	7|
||	@digidigo|	5|
||	@cuongdo|	5|
||	@UnicycleJonathan|	5|
||	@cvibhagool|	5|
||	@andrewhyde|	5|
||	@bretfunk|	5|
||	@jlgoldman|	4|
||	@endlist|	3|
||	@acal|	3|
||	@jsulinski|	3|
||	@nsimon|	2|
||	@jyotsna1820|	2|
||	@geeogi|	2|
||	@inkredabull|	2|
||	@AustinVirts|	2|
||	@jessieay|	2|
||	@Zero-1729|	1|
||	@avidsapp|	1|
||	@Yayap13|	1|
||	@kkomaz|	1|
||	@lastmjs|	1|
||	@Natasha08|	1|
||	@Chun-Lin|	1|
||	@conejoninja|	1|
||	@shoutoutloud|	1|
||	@royalharsh|	1|
||	@that1guy|	1|

### CODE REVIEW

**Comment by joshfraser** [comment]
Currently deployed to https://josh-originprotocol-com.herokuapp.com/en/team to make it easier to review. The styling isn't great, but it's a stop-gap until we have a new design.

**Comment by micahalcorn** [comment]
@joshfraser I like it! Did you mean to leave in the commented-out section? Do we need to get Aure to make an open-source contribution so that he isn't gone from the page?

**Comment by joshfraser** [comment]
@micahalcorn left the comment-out section on purpose until we get the sign-off from you & Aure (who should definitely make an open-source contribution, but I'm fine hard-coding him back in the meantime)

**Comment by davecraige** [comment]
Very cool

**Comment by joshfraser** [comment]
@coleman415 I fixed it, but for future reference, you need to add a `headshot-` prefix to our community members headshot images.

**Pull request merged**
